apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: fs-02006be24bcfd519d
 