apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx
    tier: frontend
spec:
# modify repicas according to your case
  replicas: 3
  selector:
  # these are used to select the pod to create repicas
    matchlabels:
      tier: frontend
      app: nginx
  # this is pod defination
    template:
      metadata:
        labels:
          tier: frontend
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx